# Generated by Django 2.2.12 on 2020-05-22 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=32, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Slug')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('dark_background', models.BooleanField(default=False, verbose_name='Dark Background')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('main_image', models.ImageField(default='default_project_img.jpg', upload_to='projects', verbose_name='Main Image')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('credits', models.CharField(blank=True, max_length=1024, verbose_name='Credits')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('content', models.TextField(verbose_name='Content')),
                ('fix_autoscale', models.BooleanField(default=False, help_text="Stop Safari browser in iPhones to zoom in form inputs automatically, but maintaining the user's hability to zoom in manually.", verbose_name='Fix Autoscale')),
                ('custom_font', models.BooleanField(default=False, verbose_name='Custom Font')),
                ('custom_css', models.BooleanField(default=False, verbose_name='Custom CSS')),
                ('custom_js', models.BooleanField(default=False, verbose_name='Custom JavaScript')),
                ('article_images', models.ManyToManyField(blank=True, to='file_tools.ImageUpload', verbose_name='Article Images')),
                ('categories', models.ManyToManyField(blank=True, to='projects.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
