# Generated by Django 2.2.6 on 2019-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Slug')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('dark_background', models.BooleanField(default=False, verbose_name='Dark Background')),
                ('highest_score', models.IntegerField(default=0, verbose_name='Highest Score')),
                ('downloads', models.IntegerField(default=0, verbose_name='Downloads')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
