# Generated by Django 2.2.6 on 2019-10-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
