# Generated by Django 2.2.10 on 2020-03-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200229_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(default='default_project_img.jpg', upload_to='projects', verbose_name='Main Image'),
        ),
    ]
