# Generated by Django 2.2.10 on 2020-03-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_css',
            field=models.BooleanField(default=False, verbose_name='Custom CSS'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_js',
            field=models.BooleanField(default=False, verbose_name='Custom JavaScript'),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
