# Generated by Django 2.2.4 on 2019-09-10 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=512, null=True, verbose_name='Subtitle')),
                ('light_title_text', models.BooleanField(default=False, verbose_name='Light Title Text')),
                ('main_image', models.ImageField(default='posts/default.jpg', upload_to='posts', verbose_name='Main Image')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('content', models.TextField(verbose_name='Content')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
