# Generated by Django 2.2.6 on 2019-10-08 03:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted_year_month',
            field=models.DateField(default=blog.models.year_month_now),
        ),
    ]
