# Generated by Django 2.2.10 on 2020-02-26 00:35

from django.db import migrations, models
from ..models import Post
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_featured'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Post.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='light_title_text',
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=128, verbose_name='Slug'),
        ),
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted_year_month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Main Image'),
        ),
    ]
