# Generated by Django 2.2.10 on 2020-02-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200225_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='default_post_img.jpg', upload_to='posts', verbose_name='Main Image'),
        ),
    ]
