# Generated by Django 2.2.10 on 2020-03-01 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200229_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted_year_month',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Posted Year/Month'),
        ),
    ]
