# Generated by Django 3.2.10 on 2021-12-10 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='Slug')),
                ('custom', models.BooleanField(verbose_name='Custom Slug')),
                ('full_uri', models.URLField(max_length=1024, verbose_name='Full URI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'URL Shortener',
                'verbose_name_plural': 'URL Shorteners',
                'ordering': ['-created_at'],
            },
        ),
    ]
